# Generated by Django 5.1.7 on 2025-03-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512)),
                ('page_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='pdf_images/')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
