# Generated by Django 5.1.7 on 2026-09-30 04:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


STATE_OPERATIONS = [
    migrations.CreateModel(
        name='AffectedSite',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('site_name', models.CharField(max_length=100, unique=True, verbose_name='发病部位名称')),
            ('name_en', models.CharField(max_length=100, unique=True, verbose_name='发病部位英文名称')),
            ('description', models.TextField(blank=True, null=True, verbose_name='部位描述')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ],
        options={
            'verbose_name': '发病部位',
            'verbose_name_plural': '发病部位',
            'db_table': 'h_affected_site',
        },
    ),
    migrations.CreateModel(
        name='CellData',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('disease_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='疾病标准名称')),
            ('disease_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='疾病完整名称/子类型')),
            ('abbreviation', models.CharField(blank=True, max_length=50, null=True, verbose_name='疾病缩写')),
            ('dataset_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据集来源')),
            ('dataset_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据集唯一标识')),
            ('tissue', models.CharField(blank=True, max_length=50, null=True, verbose_name='组织类型')),
            ('sample_size', models.IntegerField(blank=True, null=True, verbose_name='样本量')),
            ('cell_count', models.IntegerField(blank=True, null=True, verbose_name='细胞总数')),
            ('remarks', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ('batch', models.CharField(blank=True, max_length=8, null=True, verbose_name='批次日期')),
            ('file_name', models.CharField(blank=True, max_length=8, null=True, verbose_name='文件名称')),
        ],
        options={
            'verbose_name': '细胞研究数据',
            'verbose_name_plural': '细胞研究数据',
            'db_table': 'cell_data',
        },
    ),
    migrations.CreateModel(
        name='Disease',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name_en', models.CharField(max_length=100, verbose_name='疾病英文名称')),
            ('abbreviation', models.CharField(max_length=20, verbose_name='疾病缩写')),
            ('features', models.TextField(blank=True, null=True, verbose_name='病变特征描述')),
            ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        ],
        options={
            'verbose_name': '疾病',
            'verbose_name_plural': '疾病',
            'db_table': 'h_disease',
        },
    ),
    migrations.CreateModel(
        name='DiseaseSiteRelation',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ],
        options={
            'verbose_name': '疾病与发病部位关联',
            'verbose_name_plural': '疾病与发病部位关联',
            'db_table': 'h_disease_site_relation',
        },
    ),
    migrations.CreateModel(
        name='H5File',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=255, verbose_name='文件名')),
            ('path', models.CharField(max_length=1024, verbose_name='完整路径')),
            ('relative_path', models.CharField(max_length=1024, verbose_name='相对路径')),
            ('create_time', models.DateTimeField(auto_now_add=True)),
            ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
            ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
        ],
        options={
            'verbose_name': 'H5文件',
            'verbose_name_plural': 'H5文件',
            'db_table': 'h5_files',
        },
    ),
    migrations.AddField(
        model_name='pdfimage',
        name='create_time',
        field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='pdfimage',
        name='image_height',
        field=models.CharField(default='', max_length=512),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='pdfimage',
        name='image_width',
        field=models.CharField(default='', max_length=512),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='pdfimage',
        name='is_pdf',
        field=models.CharField(default='', max_length=512),
        preserve_default=False,
    ),
    migrations.AlterField(
        model_name='pdfimage',
        name='image',
        field=models.FileField(blank=True, null=True, upload_to='pdf_images/'),
    ),
    migrations.AlterModelTable(
        name='pdfimage',
        table='tisch_api_pdfimage',
    ),
    migrations.AddIndex(
        model_name='disease',
        index=models.Index(fields=['abbreviation'], name='idx_abbreviation'),
    ),
    migrations.AddIndex(
        model_name='disease',
        index=models.Index(fields=['name_en'], name='idx_name_en'),
    ),
    migrations.AddField(
        model_name='diseasesiterelation',
        name='disease',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tisch_api.disease', verbose_name='疾病ID'),
    ),
    migrations.AddField(
        model_name='diseasesiterelation',
        name='site',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tisch_api.affectedsite', verbose_name='部位ID'),
    ),
    migrations.AddIndex(
        model_name='h5file',
        index=models.Index(fields=['name'], name='h5file_name_idx'),
    ),
    migrations.AddIndex(
        model_name='h5file',
        index=models.Index(fields=['path'], name='h5file_path_idx'),
    ),
    migrations.AlterUniqueTogether(
        name='diseasesiterelation',
        unique_together={('disease', 'site')},
    ),
]


def complete_schema(apps, schema_editor):
    """Create absent public tables; preserve manually provisioned production data.

    Existing tables are never dropped, renamed, rebuilt or bulk-updated. Missing
    PDF columns are added with safe defaults only on incomplete installations.
    Equivalent indexes are retained regardless of their legacy index names.
    """
    from django.db.migrations.state import ProjectState
    state = ProjectState.from_apps(apps)
    for operation in STATE_OPERATIONS:
        operation.state_forwards('tisch_api', state)
    final_apps = state.apps
    connection = schema_editor.connection
    tables = set(connection.introspection.table_names())
    for name in ['AffectedSite', 'CellData', 'Disease', 'H5File', 'DiseaseSiteRelation']:
        model = final_apps.get_model('tisch_api', name)
        if model._meta.db_table not in tables:
            schema_editor.create_model(model)
            tables.add(model._meta.db_table)
    model = final_apps.get_model('tisch_api', 'PDFImage')
    with connection.cursor() as cursor:
        columns = {column.name for column in connection.introspection.get_table_description(cursor, model._meta.db_table)}
    incomplete_installation = not {'create_time', 'image_height', 'image_width', 'is_pdf'}.issubset(columns)
    for name in ['create_time', 'image_height', 'image_width', 'is_pdf']:
        if name in columns:
            continue
        field = model._meta.get_field(name).clone()
        field.set_attributes_from_name(name)
        field.model = model
        field.default = django.utils.timezone.now if name == 'create_time' else ''
        schema_editor.add_field(model, field)
    if incomplete_installation:
        # Only fresh/incomplete installations need the original 0001 image
        # column brought into line with the nullable FileField model. Complete
        # manually provisioned production tables are left unchanged.
        old_field = models.ImageField(upload_to='pdf_images/')
        old_field.set_attributes_from_name('image')
        old_field.model = model
        schema_editor.alter_field(model, old_field, model._meta.get_field('image'))
    # Preserve existing equivalent column indexes instead of duplicating large
    # production indexes merely to change their names.
    for name in ['PDFImage', 'Disease', 'H5File']:
        model = final_apps.get_model('tisch_api', name)
        with connection.cursor() as cursor:
            indexes = connection.introspection.get_constraints(cursor, model._meta.db_table)
        for index in model._meta.indexes:
            columns = [model._meta.get_field(field).column for field in index.fields]
            if any(value.get('index') and value.get('columns') == columns for value in indexes.values()):
                continue
            schema_editor.add_index(model, index)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [('tisch_api', '0005_pdf_relative_path_index')]
    operations = [migrations.SeparateDatabaseAndState(
        state_operations=STATE_OPERATIONS,
        database_operations=[migrations.RunPython(complete_schema, migrations.RunPython.noop)],
    )]
